### ISSUE TITLE
As a user, I want to login so I can use the app.

### ISSUE THREAD

**Issue by alexacarleo** [mshaffer9/ReelMarkets#2]
**Story/Task Details**

- [x] Design Login screen

- [x] Write login controller

**Acceptance Test Scenario**
Given: A registered user is in the system
When: The user enters the correct username and password
Then: The user is taken to the home page

Given: A registered user in the system
When: The user enters either an incorrect username or password
Then: The system produces an error message

Given: An unregistered user in the system
When: The user enter a username and password
Then: The system produces an error message, prompting the user to create an account

**Done Done Criteria:**

- [x] Team has approved the UI design

- [x] UI elements have been created and given to team

- [x] Code is merged into master branch

- [x] Acceptance scenarios are passing

**Comment by alexacarleo** [comment]
![login button](https://cloud.githubusercontent.com/assets/3826457/22314680/84674884-e330-11e6-8514-50c3d1dcd1bf.png)
![login shadow box](https://cloud.githubusercontent.com/assets/3826457/22314679/8460faba-e330-11e6-989c-1979b36ffe7d.png)

**Comment by alexacarleo** [comment]
Background color: e6e6e6

**Comment by vgupta61** [comment]
For the third Acceptance Test Scenario, I think the response should be a vague "Invalid login", similar to if the user enters an incorrect username + password.
