### ISSUE TITLE
As a user, I want to delete my account to protect my information.

### ISSUE THREAD

**Issue by alexacarleo** [mshaffer9/ReelMarkets#6]
**Story/Task Details**
- [x] Add Delete Account button to profile page
- [x] Add backend logic to remove user from user map

**Acceptance Test Scenario**
Given: A registered user in their profile
When: The Delete Account button is selected
Then: The user's information is removed from the user map

**Done Done Criteria:**
- [x] User's information is removed successfully from user map
- [x] Code is merged to master branch
- [x] User can no longer log in to app

**Comment by vgupta61** [comment]
Added code to prevent deletion of moderator and admin account. We can change it later.
